syntax = "proto3";

package identity;

import "common/base.proto";
import "common/pagination.proto";
import "google/api/annotations.proto";
import "identity/types.proto";

option go_package = "github.com/dizzrt/dauth/api/gen/identity;identity";

message CreateUserRequest {
  string username = 1;
  string password = 2;
  optional string phone = 3;
  optional string email = 4;
  optional string nickname = 5;
  optional UserStatus status = 6;
  optional UserExtend extend = 7;

  common.Base base = 255;
}

message CreateUserResponse {
  User user = 1;

  common.BaseResp base_resp = 255;
}

message GetUserRequest {
  uint32 uid = 1;

  common.Base base = 255;
}

message GetUserResponse {
  User user = 1;

  common.BaseResp base_resp = 255;
}

message GetUserByNameRequest {
  string username = 1;

  common.Base base = 255;
}

message GetUserByNameResponse {
  User user = 1;

  common.BaseResp base_resp = 255;
}

message ListUsersRequest {
  common.Pagination pagination = 254;
  common.Base base = 255;
}

message ListUsersResponse {
  repeated User users = 1;

  common.Pagination pagination = 254;
  common.BaseResp base_resp = 255;
}

message VerifyPasswordRequest {
  string password = 1;
  optional uint32 uid = 2;
  optional string username = 3;
  optional string email = 4;
  optional string phone = 5;

  common.Base base = 255;
}

message VerifyPasswordResponse {
  bool ok = 1;
  optional User user = 2;
  optional bool is_locked = 3;
  optional int32 remaining_attempts = 4;
  optional int64 remaining_lock_time = 5;

  common.BaseResp base_resp = 255;
}

message UpdateUserStatusRequest {
  uint32 uid = 1;
  UserStatus status = 2;

  common.Base base = 255;
}

message UpdateUserStatusResponse {
  UserStatus status = 1; // new status

  common.BaseResp base_resp = 255;
}

service UserService {
  // CreateUser creates a new user.
  rpc CreateUser(CreateUserRequest) returns (CreateUserResponse) {
    option (google.api.http) = {
      post: "/identity/user"
      body: "*"
    };
  }

  // GetUser gets a user by ID.
  rpc GetUser(GetUserRequest) returns (GetUserResponse) {
    option (google.api.http) = {get: "/identity/user/{uid}"};
  }

  // GetUserByName gets a user by username.
  rpc GetUserByName(GetUserByNameRequest) returns (GetUserByNameResponse) {}

  // ListUsers lists all users.
  rpc ListUsers(ListUsersRequest) returns (ListUsersResponse) {
    option (google.api.http) = {get: "/identity/users"};
  }

  // VerifyPassword verifies a user's password.
  rpc VerifyPassword(VerifyPasswordRequest) returns (VerifyPasswordResponse) {}

  // UpdateUserStatus updates a user's status.
  rpc UpdateUserStatus(UpdateUserStatusRequest) returns (UpdateUserStatusResponse) {
    option (google.api.http) = {
      patch: "/identity/user/{uid}/status"
      body: "*"
    };
  }
}
