// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/dizzrt/dauth/internal/conf"
	"github.com/dizzrt/dauth/internal/iface"
	"github.com/dizzrt/dauth/internal/server"
	"github.com/dizzrt/ellie"
	"github.com/dizzrt/ellie/log"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.LogWriter) (*ellie.App, func(), error) {
	exampleHandler := iface.NewExampleHandler()
	grpcServer := server.NewGRPCServer(bootstrap, logger, exampleHandler)
	httpServer := server.NewHTTPServer(bootstrap, logger, exampleHandler)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
