// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/dizzrt/dauth/internal/application"
	"github.com/dizzrt/dauth/internal/conf"
	"github.com/dizzrt/dauth/internal/domain/user/biz"
	"github.com/dizzrt/dauth/internal/handler"
	"github.com/dizzrt/dauth/internal/infra/common"
	"github.com/dizzrt/dauth/internal/infra/repo"
	"github.com/dizzrt/dauth/internal/server"
	"github.com/dizzrt/ellie"
	"github.com/dizzrt/ellie/log"
)

// Injectors from wire.go:

func wireApp(bootstrap *conf.Bootstrap, logger log.LogWriter) (*ellie.App, func(), error) {
	db := common.NewDB()
	userRepo := repo.NewUserRepoImpl(db)
	userBiz := biz.NewUserBiz(userRepo)
	userApplication := application.NewUserApplication(userBiz)
	userHandler := handler.NewUserHandler(userApplication)
	grpcServer := server.NewGRPCServer(bootstrap, logger, userHandler)
	httpServer := server.NewHTTPServer(bootstrap, logger, userHandler)
	app := newApp(logger, grpcServer, httpServer)
	return app, func() {
	}, nil
}
