// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package cmd

import (
	"github.com/dizzrt/dauth/internal/application"
	"github.com/dizzrt/dauth/internal/conf"
	"github.com/dizzrt/dauth/internal/domain/identity/biz"
	"github.com/dizzrt/dauth/internal/handler"
	"github.com/dizzrt/dauth/internal/infra/foundation"
	"github.com/dizzrt/dauth/internal/infra/repo/core"
	"github.com/dizzrt/dauth/internal/infra/repo/impl/identity"
	"github.com/dizzrt/dauth/internal/server"
	"github.com/dizzrt/ellie"
)

// Injectors from wire.go:

func wireApp() (*ellie.App, func(), error) {
	appConfig := conf.GetAppConfig()
	logWriter := foundation.NewLogger(appConfig)
	tracerProvider, cleanup, err := foundation.NewTracerProvider(appConfig)
	if err != nil {
		return nil, nil, err
	}
	registrar := foundation.NewRegistrar(appConfig)
	db := foundation.NewDB(appConfig)
	repoCore := core.NewRepoCore(db)
	userRepo := identity.NewUserRepoImpl(repoCore)
	userBiz := biz.NewUserBiz(userRepo)
	identityApplication := application.NewIdentityApplication(userBiz)
	identityHandler := handler.NewIdentityHandler(identityApplication)
	grpcServer := server.NewGRPCServer(appConfig, logWriter, identityHandler)
	httpServer := server.NewHTTPServer(appConfig, logWriter, identityHandler)
	app, cleanup2, err := newApp(logWriter, tracerProvider, registrar, grpcServer, httpServer)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	return app, func() {
		cleanup2()
		cleanup()
	}, nil
}
